const Map<String, String> countries = {
  'United States': 'USA',
  'Canada': 'CAN',
  'Finland': 'FIN',
  'Sweden': 'SWE',
  'Czech Republic': 'CZE',
  'Russia': 'RUS',
  'Switzerland': 'SUI',
  'Slovakia': 'SVK',
  'Germany': 'GER',
  'Denmark': 'DEN',
  'Norway': 'NOR',
  'Belarus': 'BLR',
  'Latvia': 'LAT',
  'France': 'FRA',
  'Austria': 'AUT',
  'Slovenia': 'SLO',
  'Kazakhstan': 'KAZ',
  'United Kingdom': 'GBR',
  'Italy': 'ITA',
  'Hungary': 'HUN',
  'Ukraine': 'UKR',
  'Poland': 'POL',
  'Japan': 'JPN',
  'South Korea': 'KOR',
};
