default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight using API key"
  lane :beta do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      clean: true,
      api_key: app_store_connect_api_key(
        key_id: ENV['APPSTORE_CONNECT_API_KEY_ID'],
        issuer_id: ENV['APPSTORE_CONNECT_API_KEY_ISSUER'],
        key_filepath: "../AuthKey.p8"
      )
    )
    upload_to_testflight(
      api_key: app_store_connect_api_key(
        key_id: ENV['APPSTORE_CONNECT_API_KEY_ID'],
        issuer_id: ENV['APPSTORE_CONNECT_API_KEY_ISSUER'],
        key_filepath: "../AuthKey.p8"
      )
    )
  end
end
