default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight using API key"
  lane :beta do
    api_key = app_store_connect_api_key(
        key_id: ENV["APPSTORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APPSTORE_CONNECT_API_KEY_ISSUER"],
        key_filepath: ENV["APPSTORE_CONNECT_API_KEY_CONTENT"] # actually the path to .p8 file
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      api_key: api_key, # <-- pass the api_key variable here
      skip_codesigning: true
    )

    upload_to_testflight(
      api_key: api_key
    )
  end
end

